<?php echo '<' . '?xml version="1.0" encoding="UTF-8"?' . '>'; ?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
     xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:taxo="http://purl.org/rss/1.0/modules/taxonomy/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" version="2.0">
    <channel>
        <atom:link href="<?php echo $this->getUri($this->getCurrentPage()->getUrl()); ?>" rel="self" type="application/rss+xml" />
        <title><?php echo \BackBee\Utils\StringUtils::toXmlCompliant($this->getCurrentPage()->getTitle()) . ' - ' . \BackBee\Utils\StringUtils::toXmlCompliant($this->sitename()); ?></title>
        <link><?php echo $this->getUri($this->getCurrentPage()->getUrl(), ''); ?></link>
        <description><?php echo (null !== $this->getCurrentPage()->getMetadata() && null !== $this->getCurrentPage()->getMetadata()->get('description')) ? \BackBee\Utils\StringUtils::toXmlCompliant($this->getCurrentPage()->getMetadata()->get('description')->getAttribute('content')) : ''; ?></description>
        <pubDate><?php echo date('D, d M Y H:i:s O'); ?></pubDate>
        <lastBuildDate><?php echo date('D, d M Y H:i:s O'); ?></lastBuildDate>
        <ttl>15</ttl>
        <?php echo $this->container()->first(); ?>
    </channel>
</rss>
