<?php

/*
 * Copyright (c) 2011-2021 Lp Digital
 *
 * This file is part of BackBee Standalone.
 *
 * BackBee is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with BackBee Standalone. If not, see <https://www.gnu.org/licenses/>.
 */

namespace BackBeePlanet\Sitemap\Query;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Interface CollectorInterface
 *
 * A collector builds an array of pages regarding a provided set of discriminators.
 * The array items are indexed by a site name URL generated by the provided
 * URL pattern.
 *
 * @package BackBeePlanet\Sitemap\Query
 */
interface CollectorInterface extends ContainerAwareInterface
{
    /**
     * Sets the container.
     *
     * @param ContainerInterface|null $container A ContainerInterface instance
     */
    public function setContainer(ContainerInterface $container = null);

    /**
     * Sets the URL pattern for this collector.
     *
     * @param string $urlPattern The URL pattern to set.
     */
    public function setUrlPattern(string $urlPattern);

    /**
     * Sets the selection limits.
     *
     * @param array $limits An array of limits.
     */
    public function setLimits(array $limits);

    /**
     * Collects objects and organizes them regarding discriminators.
     *
     * @param array $preset Optional, an array of preset values for discriminators.
     *
     * @return array An array of matching objects indexed by their sitemap URLs.
     */
    public function collect(array $preset = []): array;

    /**
     * Gets an array of discriminators accepted by this collector.
     *
     * @return array An array of accepted discriminators.
     */
    public function getAcceptedDiscriminators(): array;
}
