bundle:
    name: BackBee Cloud CorePHP
    enable: true
    bundle_loader_recipes:
        event: [ BackBeeCloud\EntryPoint, onLoadEvents ]
        custom: [ BackBeeCloud\EntryPoint, onLoadConfigurations ]