graph:
    name: BackBee
    website_name: backbee
    website_description: Backbee
    website_search: /search
    website_search_term_string: '?q='
    logo: ~
    image: ~
    social_profiles: [ https://twitter.com, https://www.facebook.com, https://www.linkedin.com ]
    twitter_card: summary_large_image
google_website_verification: https://www.google.com/webmasters/verification/home?hl=en
google_search_console: https://search.google.com/search-console
mapping_schema_types:
    Article: [ home, blank, article ]