graph:
    name: BackBee
    website_name: backbee
    website_description: Backbee
    website_search: /search
    website_search_term_string: '?q='
    logo: https://www.backbee.com/resources/integration/html/mstile-70x70.png
    image: https://www.backbee.com/resources/integration/html/mstile-310x310.png
    social_profiles: [ https://twitter.com, https://www.facebook.com ]
    twitter_card: summary_large_image
google_site_verification: xeNRmYBm7WOzGsdDw0NoVq0zxgQS9UXPpPEOjfKWVKQ
google_website_verification: https://www.google.com/webmasters/verification/home?hl=en
google_search_console: https://search.google.com/search-console
mapping_schema_types:
    Article: [ home, blank, article ]