parameters:
  bbapp.classcontent.exception_on_unknown_classname: false
  error.base_folder: ''
  error.404: error_404.html.twig
  error.500: error_500.html.twig
  error.default: error_default.html.twig
  cloud.default.ordered.categories: []
  cloud.override.default.categories: false
  cloud.strictly.default.categories: true

services:
  cloud.page_manager:
    class: BackBeeCloud\Entity\PageManager
    arguments: ["@bbapp"]

  cloud.content_manager:
    class: BackBeeCloud\Entity\ContentManager
    arguments: ["@em", "@classcontent.manager", "@event.dispatcher"]

  cloud.tag_manager:
    class: BackBeeCloud\Entity\TagManager
    arguments: ["@em", "@elasticsearch.manager"]

  cloud.image_listener:
    class: BackBeeCloud\Listener\ImageListener
    arguments: ["@cloud.file_handler"]

  cloud.file_handler:
    class: BackBeeCloud\ImageFilesystemHandler
    arguments: ["@bbapp"]

  user_preference.manager:
    class: BackBeeCloud\UserPreference\UserPreferenceManager
    arguments: ["@em"]

  site_option.manager:
    class: BackBeeCloud\SiteOption\OptionManager
    arguments: ["@em"]

  content.category_listener:
    class: BackBeeCloud\Listener\ContentCategoryListener
    arguments:
      - "%cloud.default.ordered.categories%"
      - "%cloud.override.default.categories%"
      - "%cloud.strictly.default.categories%"

  site_status.manager:
    class: BackBeeCloud\SiteStatusManager
    arguments: ["@em"]

  # Contact service
  contact_controller:
    class: BackBeeCloud\Controller\ContactController
    arguments: ["@bbapp"]

  # Newsletter service
  newsletter_controller:
    class: BackBeeCloud\Controller\NewsletterController
    arguments: ["@em"]

  # Search Engine service
  search_engine_controller:
    class: BackBeeCloud\Controller\SearchEngineController
    arguments: ["@renderer", "@user_preference.manager"]

  # Search service
  cloud.search_manager:
    class: BackBeeCloud\Search\SearchManager
    arguments: ["@cloud.page_manager", "@cloud.content_manager", "@em"]

  cloud.search_controller:
    class: BackBeeCloud\Controller\SearchController
    arguments: ["@cloud.search_manager", "@multilang_manager", "@routing", "@renderer"]

  # API services
  cloud.api.user_controller:
    class: BackBeeCloud\Api\Controller\UserController
    arguments: ["@bbapp"]

  cloud.api.user_preference_controller:
    class: BackBeeCloud\Api\Controller\UserPreferenceController
    arguments: ["@bbapp"]

  cloud.api.import_status_controller:
    class: BackBeeCloud\Api\Controller\ImportStatusController
    arguments: ["@em"]

  cloud.api.mailchimp_controller:
    class: BackBeeCloud\Api\Controller\MailchimpController
    arguments: ["@bbapp"]

  cloud.api.page_controller:
    class: BackBeeCloud\Api\Controller\PageController
    arguments: ["@bbapp"]

  cloud.api.content_controller:
    class: BackBeeCloud\Api\Controller\ContentController
    arguments: ["@bbapp"]

  cloud.api.page_type_controller:
    class: BackBeeCloud\Api\Controller\PageTypeController
    arguments: ["@bbapp"]

  cloud.api.tag_controller:
    class: BackBeeCloud\Api\Controller\TagController
    arguments: ["@bbapp"]

  cloud.api.site_controller:
    class: BackBeeCloud\Api\Controller\SiteController
    arguments: ["@site_status.manager"]

  # Page type services
  cloud.page_type.manager:
    class: BackBeeCloud\PageType\TypeManager
    arguments: ["@service_container", "@cloud.structure.schema_parser"]

  cloud.page_type.home_type:
    class: BackBeeCloud\PageType\HomeType
    tags:
      - { name: page.type, dispatch_event: false }

  cloud.page_type.blank_type:
    class: BackBeeCloud\PageType\BlankType
    tags:
      - { name: page.type, dispatch_event: false }

  cloud.page_type.article_type:
    class: BackBeeCloud\PageType\ArticleType
    tags:
      - { name: page.type, dispatch_event: false }

  cloud.page_type.search_result_type:
    class: BackBeeCloud\PageType\SearchResultType
    tags:
      - { name: page.type, dispatch_event: false }

  cloud.disqus_listener:
    class: BackBeeCloud\Listener\ClassContent\DisqusListener
    arguments: ["@bbapp"]

  elasticsearch.manager:
    class: BackBeeCloud\Elasticsearch\ElasticsearchManager
    arguments: ["@bbapp"]
    tags:
      - { name: worker.job_handler, dispatch_event: false }

  # MultiLang service
  multilang_manager:
    class: BackBeeCloud\MultiLang\MultiLangManager
    arguments: ["@bbapp"]
    tags:
      - { name: worker.job_handler, dispatch_event: false }

  api.multilang_controller:
    class: BackBeeCloud\Api\Controller\MultiLangController
    arguments: ["@multilang_manager", "@bbapp"]

  api.multilang.listener:
    class: BackBeeCloud\Listener\MultiLangListener
    arguments:
      - "@multilang_manager"
      - "@cloud.multilang.page_association.manager"
      - "@em"

  cloud.multilang.page_association.controller:
    class: BackBeeCloud\Api\Controller\PageAssociationController
    arguments:
      - "@bbapp"
      - "@cloud.multilang.page_association.manager"
      - "@cloud.page_manager"

  cloud.multilang.page_association.manager:
    class: BackBeeCloud\MultiLang\PageAssociationManager
    arguments:
      - "@em"
      - "@multilang_manager"
      - "@elasticsearch.manager"

  # Structure's services
  cloud.structure.schema_parser:
    class: BackBeeCloud\Structure\DefaultSchemaParser

  cloud.structure.content_builder:
    class: BackBeeCloud\Structure\ContentBuilder
    arguments: ["@service_container", "@em"]

  cloud.structure_builder:
    class: BackBeeCloud\Structure\StructureBuilder
    arguments: ["@bbapp", "@cloud.structure.schema_parser"]

  yaml_structure_dumper.manager:
    class: BackBeeCloud\Structure\YamlStructureDumperManager
    arguments: ["@bbapp"]
    tags:
      - { name: worker.job_handler, dispatch_event: false }

  structure.parameter_handler:
    class: BackBeeCloud\Structure\ContentHandler\ParameterHandler
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  structure.paragraph_handler:
    class: BackBeeCloud\Structure\ContentHandler\ParagraphHandler
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  structure.image_handler:
    class: BackBeeCloud\Structure\ContentHandler\ImageHandler
    arguments: ["@cloud.file_handler"]
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  structure.slider_handler:
    class: BackBeeCloud\Structure\ContentHandler\SliderHandler
    arguments: ["@structure.image_handler", "@structure.parameter_handler"]
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  structure.highlightcontent_handler:
    class: BackBeeCloud\Structure\ContentHandler\HighlightContentHandler
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  structure.contact_handler:
    class: BackBeeCloud\Structure\ContentHandler\ContactHandler
    arguments: ["@em"]
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  structure.socialicons_handler:
    class: BackBeeCloud\Structure\ContentHandler\SocialIconsHandler
    tags:
      - { name: structure.content_handler, dispatch_event: false }

  cloud.global_content_factory:
    class: BackBeeCloud\Structure\GlobalContentFactory
    arguments: ["@bbapp"]

  cloud.hauth.controller:
    class: BackBeeCloud\Controller\HAuthController
    arguments: ["@bbapp"]

  # Security services
  security.voter.sudo:
    class: BackBeeCloud\Security\Authorization\Voter\SudoVoter
    arguments: ["@bbapp"]

  cloud.api.acl_controller:
    class: BackBeeCloud\Api\Controller\AclController
    arguments: ["@bbapp"]

  # Search pages by tag services
  cloud.page_by_tag.manager:
    class: BackBeeCloud\Search\PageByTagManager
    arguments: ["@cloud.page_manager", "@cloud.content_manager", "@em"]

  cloud.page_by_tag.controller:
    class: BackBeeCloud\Controller\PageByTagController
    arguments: ["@cloud.page_by_tag.manager", "@multilang_manager", "@routing", "@renderer"]

  cloud.page_type.page_by_tag_result_type:
    class: BackBeeCloud\PageType\PageByTagResultType
    tags:
      - { name: page.type, dispatch_event: false }

  cloud.user_manager:
    class: BackBeeCloud\User\UserManager

  # Migrations services
  media_image.migration:
    class: BackBeeCloud\Migration\MediaImageMigration
    arguments: ["@em", "@site_status.manager", "@elasticsearch.manager"]
    tags:
      - { name: worker.job_handler, dispatch_event: false }

  # ClassContentOverrider
  cloud.classcontent_overrider:
    class: BackBeeCloud\ClassContent\ClassContentOverrider
    factory: ["BackBeeCloud\ClassContent\ClassContentOverriderFactory", createClassContentOverrider]
    arguments:
      - "@service_container"
      - "@bbapp"

  cloud.classcontent_overrider.listener:
    class: BackBeeCloud\Listener\ClassContentOverriderListener
    arguments:
      - "@cloud.classcontent_overrider"

  # ThemeColor services
  cloud.theme_color.manager:
    class: BackBeeCloud\ThemeColor\ThemeColorManager
    factory: ["BackBeeCloud\ThemeColor\ThemeColorManagerFactory", createThemeColorManager]
    arguments: ["@service_container"]

  cloud.theme_color.default:
    class: BackBeeCloud\ThemeColor\DefaultThemeColor
    tags:
      - { name: theme_color, dispatch_event: false }

  cloud.api.theme_color.controller:
    class: BackBeeCloud\Api\Controller\ThemeColorController
    arguments: ["@cloud.theme_color.manager", "@bbapp"]

  cloud.color_panel.manager:
    class: BackBeeCloud\ThemeColor\ColorPanelManager
    factory: ["BackBeeCloud\ThemeColor\ColorPanelManagerFactory", createColorPanelManager]
    arguments:
        - "@em"
        - "@cloud.theme_color.manager"

  cloud.api.color_panel.controller:
    class: BackBeeCloud\Api\Controller\ColorPanelController
    arguments: ["@cloud.color_panel.manager", "@bbapp"]

  cloud.color_panel.css_generator:
    class: BackBeeCloud\ThemeColor\ColorPanelCssGenerator
    arguments: ["@cloud.color_panel.manager", "@renderer"]

  cloud.color_panel_css_genrator.controller:
    class: BackBeeCloud\Controller\ColorPanelController
    arguments: ["@cloud.color_panel.css_generator", "@em"]

  # Design services
  cloud.design.font.manager:
    class: BackBeeCloud\Design\FontManager

  cloud.api.design.font.controller:
    class: BackBeeCloud\Api\Controller\DesignFontController
    arguments: ["@cloud.design.font.manager", "@bbapp"]
